routes/web.php
<?php

Route::resource('/note','NoteController');
Route::resource('user','UserController');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::post('user/notestore/{user}','UserController@notestore')->name('user.notestore');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function Note()
    {
      return $this->hasMany(note::class);
    }
}

app/note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class note extends Model
{
    protected $fillable = ['title','body','user_id'];
    public function user()
    {
      return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Api/AuthController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
class AuthController extends Controller
{
    public function register(Request $request)
    {
      $user = new User;
      $user->email = $request->email;
      $user->name = $request->name;
      $user->password = bcrypt($request->password);
      $user->save();
      return response([
          'status' => 'success',
          'data' => $user
         ], 200);
    }

    public function login(Request $request)
    {
        $credentials = $request->only('email', 'password');
        if ( !$token = JWTAuth::attempt($credentials)) {
                return response([
                    'status' => 'error',
                    'error' => 'invalid.credentials',
                    'msg' => 'Invalid Credentials.'
                ], 400);
        }
        return response([
                'status' => 'success',
                'token' => $token
            ]);
    }
}

app/Http/Controllers/Api/NoteController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\note;
class NoteController extends Controller
{
    function index(){
      return response()->json([
          'notes' => note::all()
      ]);
    }

    function store(Request $request){
      if(note::create($request->all()) ){
        return response()->json(['status'=>'Success']);
      }
      return response()->json(['status'=>'Error']);
    }

    public function destroy(Note $note)
    {
      if($note->delete()){
        return response()->json(['status'=>'Success']);
      }
      return response()->json(['status'=>'Error']);

    }

    public function update(Request $request,Note $note)
    {
      $data = $request->validate
      ([
        'title' => 'required|max:255',
        'body' => 'required',
      ]);
      $note->title = $data['title'];
      $note->body = $data['body'];



      if($note->save()){
        return response()->json(['status'=>'Success']);
      }
      return response()->json(['status'=>'Error']);


    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/NoteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Note;
use Illuminate\Support\Facades\Auth;

class NoteController extends Controller
{

    public function index()
    {
        return view('note.index');
    }


    public function getData()
    {
        return response()->json(['data'=>Note::select('id', 'title','body')->get()]);
    }


    public function store(Request $request)
    {
        if (Note::create($request->all())) {
            return response()->json(['status'=>true]);
        }
        return response()->json(['status'=>false]);
    }


    public function update(Request $request,Note $note)
    {
        if ($note->update($request->all())) {
            return response()->json(['status'=>true]);
        }
        return response()->json(['status'=>false]);
    }


    public function destroy(Note $note)
    {
        if ($note->delete()) {
            return response()->json(['status'=>true]);
        }
        return response()->json(['status'=>false]);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    public function index()
    {
      $users = User::all();

      return view('user/index',compact('users'));
    }


    public function create()
    {
        //
    }


    public function store(Request $request)
    {
        //
    }


    public function show(User $user)
    {
      return view('user/show',compact('user'));
    }


    public function notestore(User $user,Request $request)
    {
      $user->note()->create($request->all());
      return redirect()->back();
    }


    public function edit($id)
    {
        //
    }


    public function update(Request $request, $id)
    {
        //
    }


    public function destroy($id)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>

resources/views/layouts/errors.blade.php
@if (count($errors) > 0)
<!-- Form Error List -->
<div class="alert alert-danger">
    <strong>Whoops! Something went wrong!</strong>
    <br>
    <br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

resources/views/layouts/formModal.blade.php
<div class="container">
    <!-- Button to Open the Modal -->
    <!-- The Modal -->
    <div class="modal fade" id="{{ $id }}">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title"> {{ $title }}</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <!-- Modal body -->
                <div class="modal-body">
                  {{ $inputs }}
                </div>
                <!-- Modal footer -->
                <div class="modal-footer">
                  {{ $buttons }}

                </div>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@yield('title')</title>
    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="css/thumbnail-gallery.css" rel="stylesheet">
</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">SCNote</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    @yield('content')
    <!-- Footer -->
    <footer class="py-0.5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Social Computing Note 2018</p>
        </div>
    </footer>
    <!-- Bootstrap core JavaScript -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/vue@2.5.17/dist/vue.js"></script>
    @yield('script')

</body>

</html>

resources/views/note/create.blade.php
@extends('layouts.master')
@section('title',"{{__('pages/noteCreate.createNewTitle')}}")
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-6 col-sm-offset-3">
            <form action="{{route('note.store')}}" method="post">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="Title">{{__('pages/noteCreate.title')}}</label>
                    <input type="text" class="form-control" id="title" aria-describedby="emailHelp" placeholder="{{__('pages/noteCreate.enterTitle')}}" name="title">

        </div>
                <div class="form-group">
                    <label for="command">{{__('pages/noteCreate.command')}}</label>
                    <textarea class="form-control" id="command" placeholder="{{__('pages/noteCreate.enterCommand')}}" name="body" rows="10"></textarea>
                </div>
                @include('layouts.errors')
                <div class="row">
                    &nbsp;&nbsp;
                    <button type="submit" class="btn btn-dark">{{__('pages/noteCreate.submit')}}</button>
                    &nbsp;&nbsp;
                    <a href="{{route('note.index')}}" class="btn btn-dark">{{__('pages/noteCreate.backHome')}}</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection('content')

resources/views/note/edit.blade.php
@extends('layouts.master')
@section('title',"{{__('pages/noteCreate.createNewTitle')}}")
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-6 col-sm-offset-3">
            <form action="{{route('note.store')}}" method="post">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="Title">{{__('pages/noteCreate.title')}}</label>
                    <input type="text" class="form-control" id="title" aria-describedby="emailHelp"value="{{$note->title}}" name="title">

        </div>
                <div class="form-group">
                    <label for="command">{{__('pages/noteCreate.command')}}</label>
                    <textarea class="form-control" id="command"  name="body" rows="10">{{$note->body}}</textarea>
                </div>
                @include('layouts.errors')
                <div class="row">
                    &nbsp;&nbsp;
                    <button type="submit" class="btn btn-dark">{{__('pages/noteCreate.submit')}}</button>
                    &nbsp;&nbsp;
                    <a href="{{route('note.index')}}" class="btn btn-dark">{{__('pages/noteCreate.backHome')}}</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection('content')

resources/views/note/index.blade.php
@extends('layouts.master')
@section('title',  "{{__('pages/noteIndex.myCommands')}}")
@section('content')
   <div class="container" id="note">
        <button type="button" class="btn btn-dark btn-lg pull-right"  data-toggle="modal" data-target="#newNoteModal" v-on:click="openNewForm()">
          <i class="fa fa-plus-circle" style="font-size:16px">&nbsp;</i>
          {{__('pages/noteIndex.createNewCommand')}}
        </button>
        <h1 class="my-4 text-center text-lg-left">All Commands</h1>
        <div class="row text-center text-lg-left">
            <div class="card" style="width: 25rem;" id='noteTitle' v-for="(note,index) in noteArray">
                <div class="card-body">
                <h3 class="card-title">@{{note.title}}</h3>
                    <p class="card-text">@{{ (substr(note.body,0,200) ) }}</p>
                    <div class="row" style="position: static; bottom:0px;">
                        &nbsp;&nbsp;
                        <button  class="btn btn-danger" v-on:click="deleteeNote(index)"><i class="material-icons" style="font-size:20px">delete</i></button>


                        &nbsp;&nbsp;
                        <button v-on:click="openModifyForm(index);modifyStatus = true"class="btn btn-info" data-toggle="modal" data-target="#noteEditModal"><i class="material-icons" style="font-size:20px">edit</i>Edit</button>

                        &nbsp;&nbsp;
                        <a href="" class="btn btn-info"><i class="fa fa-inbox" style="font-size:20px"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- container -->
        @component('layouts.formModal')
    @slot('id',"newNoteModal")
    @slot('title',"Add New Note")
    @slot('inputs')
        <div class="form-group">
            <label>title</label>
            <input type="text"class="form-control" v-model="title">
        </div>
        <div class="form-group">
            <label>body</label>
            <input type="text"class="form-control" v-model="body">
        </div>
    @endslot

    @slot('buttons')
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal" v-on:click="storeNote()" v-if="!modifyStatus && !showNote">Save</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal" v-on:click="editNote(id)" v-if="modifyStatus && !showNote">Update</button>
    @endslot
@endcomponent

</div>
@endsection('content')
@section('script')
@include('note.script.index')
@endsection('script')

resources/views/note/script/index.blade.php
<script>
  var note = new Vue({
      el: '#note',
      data: {
          title: '',
          body: '',
          modifyStatus: [],
          noteArray: [],
          token: '{{csrf_token()}}'
      },
      created() {
          this.getAllNote();
      },
      methods: {
          getAllNote() {
              this.$http.get('/mo/note/getData').then(result => {
                  this.noteArray = [];
                  for (var i = 0; i < result.body.data.length; i++) {
                      this.noteArray.push({
                          id: result.body.data[i].id,
                          title: result.body.data[i].title,
                          body: result.body.data[i].body,
                          modifyStatus: false
                      });
                  }
              });
          },
          deleteNote(id) {
              this.$http.delete('/mo/note/' + this.noteArray[id].id, {
                  params: {
                      '_token': this.token
                  },
                  headers: {
                      'X-CSRF-TOKEN': this.token
                  }
              }).then(result => {
                  if (result.body.status) {
                      this.getAllNote();
                  }
              });
          },
          editNote(id) {
              this.$http.put('/mo/note/' + this.noteArray[id].id, {
                  '_token': this.token,
                  title: this.noteArray[id].title
                  body: this.noteArray[id].body
              }).then(result => {
                  if (result.body.status) {
                      this.getAllNote();
                  }

              });
          },
          storeNote() {
              this.$http.post('/mo/note', {
                  '_token': this.token,
                  title: this.title
                  body: this.body
              }).then(result => {
                  if (result.body.status) {
                      this.title = '';
                      this.body = '';
                      this.getAllNote();
                  }
              });
          },
      }
  });
</script>

resources/views/note/show.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>command #{{$note->id}}</title>
</head>

<body>
    <nav class="navbar navbar-default">
        <h1>{{__('pages/noteIndex.noteOfCommands')}}</h1>
    </nav>
    <div class="well well-lg">
        <h4>commands was writtn by:</h4>
        <h5>{{$note->user->name}}&nbsp;Email:&nbsp;{{$note->user->email}}</h5>
        <hr>
        <h3>{{$note->title}}</h3>
        <h5>{{$note->body}}</h5>
        <div class="row">
            &nbsp;
            &nbsp;
            <form action="{{route('note.destroy',['id' => $note->id])}}" method="post">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
                <button class="btn btn-danger " >{{__('pages/noteIndex.delete')}}</button>
            </form>
            &nbsp;
            &nbsp;
            <a href="{{route('note.edit' , ['id' => $note->id])}}" class="btn btn-warning">{{__('pages/noteIndex.edit')}}</a>

        </div>


    </div>
</body>

</html>

resources/views/user/index.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>{{__('pages/noteIndex.myCommands')}}</title>
</head>

<body>
    <nav class="navbar navbar-default">
        <h1>{{__('pages/noteIndex.noteOfCommands')}}</h1>
    </nav>
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    <button type="button" class="btn btn-primary btn-lg" onclick="location.href='{{route('note.create')}}'">{{__('pages/noteIndex.createNewCommand')}}</button>
    <br>
    <br>


    <ul style="list-style-type:none">
        @foreach ($users as $note)
        <div class="well well-lg">
            <li>
                <h3>{{$note->name}}</h3>
                <h5>{{$note->email}}</h5>
                <div class="row">
                    &nbsp;
                    &nbsp;
                    <form action="{{route('note.destroy',['id' => $note->id])}}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <button class="btn btn-danger " >{{__('pages/noteIndex.delete')}}</button>
                    </form>
                    &nbsp;
                    &nbsp;
                    <a href="{{route('note.edit' , ['id' => $note->id])}}" class="btn btn-warning">{{__('pages/noteIndex.edit')}}</a>
                    &nbsp;
                    &nbsp;
                    <a href="{{route('user.show' , ['id' => $note->id])}}" class="btn btn-info">{{__('pages/noteIndex.show')}}</a>
                </div>


            </li>
        </div>
        @endforeach
    </ul>
</body>

</html>

resources/views/user/show.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>command #</title>
</head>

<body>
    <nav class="navbar navbar-default">
        <h1>{{__('pages/noteIndex.noteOfCommands')}}</h1>
    </nav>
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    <div class="row">
        <form action="{{route('user.notestore',[$user->id])}}" method="post">
            {{csrf_field()}}
            <div class="form-group">
                <label for="Title">{{__('pages/noteCreate.title')}}</label>
                <input type="text"  id="title" aria-describedby="emailHelp" placeholder="{{__('pages/noteCreate.enterTitle')}}" name="title">

            </div>
            <div class="form-group">
                <label for="command">{{__('pages/noteCreate.command')}}</label>
                <textarea class="form-control" id="command" placeholder="{{__('pages/noteCreate.enterCommand')}}" name="body" rows="3"></textarea>
            </div>
            @include('layouts.errors')
            <div class="row">

                <button type="submit" class="btn btn-primary">{{__('pages/noteCreate.submit')}}</button>

                <a href="{{route('note.index')}}" class="btn btn-primary">{{__('pages/noteCreate.backHome')}}</a>
            </div>
        </form>
    </div>
    <div class="well well-lg">
        <h4>commands was writtn by:</h4>
        <h5>{{$user->name}}&nbsp;Email:&nbsp;{{$user->email}}</h5>
        <hr>
        <ul style="list-style-type:none">
            @foreach ($user->note as $note)
            <div class="well well-lg">
                <li>
                    <h3>{{$note->title}}</h3>
                    <h5>{{$note->body}}</h5>
                    <div class="row">
                        &nbsp;
                        &nbsp;
                        <form action="{{route('note.destroy',['id' => $note->id])}}" method="post">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button class="btn btn-danger " >{{__('pages/noteIndex.delete')}}</button>
                        </form>
                        &nbsp;
                        &nbsp;
                        <a href="{{route('note.edit' , ['id' => $note->id])}}" class="btn btn-warning">{{__('pages/noteIndex.edit')}}</a>
                        &nbsp;
                        &nbsp;
                        <a href="{{route('note.show' , ['id' => $note->id])}}" class="btn btn-info">{{__('pages/noteIndex.show')}}</a>
                    </div>
                </li>
            </div>
            @endforeach
        </ul>
</body>
</html>